name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      #Install Dependencies
      - name: Install dependencies for server
        working-directory: ./server
        run: npm install

      # Step 5: Build the project
      - name: Build the project
        working-directory: ./server
        run: npm run build

      # Step 4: Compress the build directory (excluding node_modules)
      - name: Archive the build output
        run: tar -czf app.tar.gz . --exclude=server/node_modules

      # Step 5: Deploy to the EC2 server
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
        with:
          source: "app.tar.gz" # Only push the compressed build archive
          target: "${{ secrets.TARGET_DIR }}/app.tar.gz"

      # Step 6: Execute remote SSH commands to set up the server
      - name: Execute SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            tar -xzf app.tar.gz
            pwd
            # npm install --production
            # rm app.tar.gz
            touch deployment.txt
            # Restart your application here, e.g., using PM2 or another process manager
